name: pr-gate
on:
  pull_request:
    branches: [ "pr-check" ]
  workflow_dispatch:
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v8
      - uses: actions/setup-python@v8
        with:
         python-version: '3.12'
      - name: Run the check
        run: check.py
